[workspace]
resolver = "2"
members = ["crates/fire-ui-fonts", "crates/fire-ui", "crates/fire-ui-widgets", "crates/fire-ui-native", "examples/studio", "crates/fire-ui-gl", "crates/fire-ui-cairo", "crates/fire-ui-text"]

[workspace.package]
version = "0.7.0"
edition = "2021"
rust-version = "1.88"
license = "MIT"
repository = "https://github.com/sobir-git/fire-ui"
keywords = ["gui", "ui", "widgets", "native", "graphics"]
categories = ["gui", "graphics"]

[workspace.dependencies]
fire-ui-fonts = { version = "0.7.0", path = "crates/fire-ui-fonts" }
fire-ui = { version = "0.7.0", path = "crates/fire-ui" }
fire-ui-widgets = { version = "0.7.0", path = "crates/fire-ui-widgets" }
fire-ui-native = { version = "0.7.0", path = "crates/fire-ui-native", default-features = false }
fire-ui-gl = { version = "0.7.0", path = "crates/fire-ui-gl" }
fire-ui-cairo = { version = "0.7.0", path = "crates/fire-ui-cairo" }

fire-ui-text = { version = "0.7.0", path = "crates/fire-ui-text" }

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
strip = true

[profile.dev]
opt-level = 1
