[workspace]
resolver = "2"
members = ["crates/fire-ui", "crates/fire-ui-widgets", "crates/fire-ui-native", "examples/studio"]

[workspace.package]
version = "0.5.0"
edition = "2021"
rust-version = "1.88"
license = "MIT"
repository = "https://github.com/sobir-git/fire-ui"
keywords = ["gui", "ui", "widgets", "native", "graphics"]
categories = ["gui", "graphics"]

[workspace.dependencies]
fire-ui = { version = "0.5.0", path = "crates/fire-ui" }
fire-ui-widgets = { version = "0.5.0", path = "crates/fire-ui-widgets" }
fire-ui-native = { version = "0.5.0", path = "crates/fire-ui-native" }

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
strip = true

[profile.dev]
opt-level = 1
