[package]
name = "fire-ui-gl"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Optional OpenGL renderer and text resources for Fire UI"
readme = "README.md"
[features]
default = ["x11"]
x11 = ["fire-ui-native/x11", "glutin-winit/x11", "glutin-winit/glx"]
bitmap-fonts = ["femtovg/image-loading", "dep:image"]
raster-text = ["femtovg/swash"]
[dependencies]
ttf-parser = "0.25"
image = { version="0.25", default-features=false, features=["png"], optional=true }
fire-ui-fonts.workspace = true
fire-ui.workspace = true
fire-ui-native = { workspace = true, default-features = false }
winit = { version = "0.30", default-features = false, features = ["rwh_06"] }
glutin = { version = "0.32", default-features = false }
glow = "0.18"
glutin-winit = { version = "0.5", default-features = false }
raw-window-handle = "0.6"
femtovg = { version = "0.27", default-features = false }
[target.'cfg(target_os = "windows")'.dependencies]
glutin-winit = { version = "0.5", default-features = false, features = ["wgl"] }
