[package]
name = "fire-ui-studio"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
fire-ui.workspace = true
fire-ui-widgets.workspace = true
fire-ui-native = { workspace = true, features = ["accessibility", "inspection", "clipboard", "bitmap-fonts"] }
