[package]
name = "fire-ui-native"
version = "0.1.0"
edition = "2021"
[dependencies]
fire-ui={path="../fire-ui"}
winit="0.30"
glutin="0.32"
glutin-winit="0.5"
raw-window-handle="0.6"
femtovg={version="0.9",default-features=false}
arboard={version="3",default-features=false}
unicode-segmentation="1.12"
accesskit_winit = "0.33.2"
accesskit = "0.24"
native-dialog = "0.7"
